my_string = input('Введите любую строку: ')
print('в введенной строке ', len(my_string), 'символов')
print(my_string.upper())
print(my_string.lower())
my_string = my_string.replace(' ', '')
print(my_string)
